CREATE DATABASE "cleaningCompanyDB"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Ukrainian_Ukraine.1251'
    LC_CTYPE = 'Ukrainian_Ukraine.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

-- Table: public.consumables

-- DROP TABLE public.consumables;

CREATE TABLE IF NOT EXISTS public.consumables
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    comment character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    consumables_id integer,
    CONSTRAINT consumables_pkey PRIMARY KEY (id),
    CONSTRAINT fkavp714glbrb2g9vce8u7o6k30 FOREIGN KEY (consumables_id)
    REFERENCES public."position" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE public.consumables
    OWNER to postgres;

-- Table: public.person

-- DROP TABLE public.person;

CREATE TABLE IF NOT EXISTS public.person
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    full_name character varying(255) COLLATE pg_catalog."default",
    manager_id integer,
    name character varying(255) COLLATE pg_catalog."default",
    outer_id character varying(255) COLLATE pg_catalog."default",
    phone_number integer,
    CONSTRAINT person_pkey PRIMARY KEY (id)
    )

    TABLESPACE pg_default;

ALTER TABLE public.person
    OWNER to postgres;

-- Table: public.point

-- DROP TABLE public.point;

CREATE TABLE IF NOT EXISTS public.point
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    adress character varying(255) COLLATE pg_catalog."default",
    comment character varying(255) COLLATE pg_catalog."default",
    contact_number character varying(255) COLLATE pg_catalog."default",
    contact_person character varying(255) COLLATE pg_catalog."default",
    latitude double precision,
    longitude double precision,
    name character varying(255) COLLATE pg_catalog."default",
    outer_id character varying(255) COLLATE pg_catalog."default",
    point_id integer,
    CONSTRAINT point_pkey PRIMARY KEY (id),
    CONSTRAINT fkgcjr6m7j0lgwwi635rfhoxsha FOREIGN KEY (point_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE public.point
    OWNER to postgres;

-- Table: public.position

-- DROP TABLE public."position";

CREATE TABLE IF NOT EXISTS public."position"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    comment character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    position_id integer,
    CONSTRAINT position_pkey PRIMARY KEY (id),
    CONSTRAINT fkd3lo2vld6logpqevx9qjtd7ay FOREIGN KEY (position_id)
    REFERENCES public.task (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE public."position"
    OWNER to postgres;

-- Table: public.task

-- DROP TABLE public.task;

CREATE TABLE IF NOT EXISTS public.task
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    date date,
    outer_id character varying(255) COLLATE pg_catalog."default",
    task_id integer,
    CONSTRAINT task_pkey PRIMARY KEY (id),
    CONSTRAINT fk4dfa9sxxcasaxugqn2a5k0jls FOREIGN KEY (task_id)
    REFERENCES public.point (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE public.task
    OWNER to postgres;