-- Database: cleaningCompanyDB

-- DROP DATABASE IF EXISTS "cleaningCompanyDB";

CREATE DATABASE "cleaningCompanyDB"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Ukrainian_Ukraine.1251'
    LC_CTYPE = 'Ukrainian_Ukraine.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

-- Table: public.consumables

-- DROP TABLE IF EXISTS public.consumables;

CREATE TABLE IF NOT EXISTS public.consumables
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    comment character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT consumables_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.consumables
    OWNER to postgres;

-- Table: public.person

-- DROP TABLE IF EXISTS public.person;

CREATE TABLE IF NOT EXISTS public.person
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    full_name character varying(255) COLLATE pg_catalog."default",
    is_manager boolean,
    name character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    manager_id bigint,
    managerid character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT person_pkey PRIMARY KEY (id),
    CONSTRAINT fkkb8fb0ej36oy25j0363bncd30 FOREIGN KEY (manager_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.person
    OWNER to postgres;

-- Table: public.point

-- DROP TABLE IF EXISTS public.point;

CREATE TABLE IF NOT EXISTS public.point
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    adress character varying(255) COLLATE pg_catalog."default",
    comment character varying(255) COLLATE pg_catalog."default",
    contact_number character varying(255) COLLATE pg_catalog."default",
    contact_person character varying(255) COLLATE pg_catalog."default",
    latitude double precision,
    longitude double precision,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT point_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.point
    OWNER to postgres;

-- Table: public.position

-- DROP TABLE IF EXISTS public."position";

CREATE TABLE IF NOT EXISTS public."position"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    comment character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    task_id bigint,
    CONSTRAINT position_pkey PRIMARY KEY (id),
    CONSTRAINT fk7m3ocd2p97symplncsd1eggmt FOREIGN KEY (task_id)
        REFERENCES public.task (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."position"
    OWNER to postgres;

-- Table: public.position_position_link

-- DROP TABLE IF EXISTS public.position_position_link;

CREATE TABLE IF NOT EXISTS public.position_position_link
(
    position_1_id bigint NOT NULL,
    position_2_id bigint NOT NULL,
    CONSTRAINT fk74px0jj1vjuo8j5aqmckxhogc FOREIGN KEY (position_1_id)
        REFERENCES public."position" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fksyiu1uyywk2fce36lt1cs14vy FOREIGN KEY (position_2_id)
        REFERENCES public."position" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.position_position_link
    OWNER to postgres;

-- Table: public.task

-- DROP TABLE IF EXISTS public.task;

CREATE TABLE IF NOT EXISTS public.task
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date,
    pointid character varying(255) COLLATE pg_catalog."default",
    point_id bigint,
    CONSTRAINT task_pkey PRIMARY KEY (id),
    CONSTRAINT fkfh00pc4k881e9lejhau5y8485 FOREIGN KEY (point_id)
        REFERENCES public.point (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.task
    OWNER to postgres;
-- Index: idx_task_point_id

-- DROP INDEX IF EXISTS public.idx_task_point_id;

CREATE INDEX IF NOT EXISTS idx_task_point_id
    ON public.task USING btree
        (point_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public.task_person_link

-- DROP TABLE IF EXISTS public.task_person_link;

CREATE TABLE IF NOT EXISTS public.task_person_link
(
    task_id bigint NOT NULL,
    person_id bigint NOT NULL,
    CONSTRAINT fk212f8cvl0kktl6uvd99f0vrfx FOREIGN KEY (person_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkl3ckxtolywhjadsw9mpffwjvi FOREIGN KEY (task_id)
        REFERENCES public.task (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.task_person_link
    OWNER to postgres;